stages:
  - build
  - deploy

build:
  image: node:latest    
  stage: build
  variables: 
    # Replace this with your site URL
    PUBLIC_URL: https://steven.meyer@students.ffhs.ch.gitlab.io/SSE_Frontend/  
  script:
    - yarn install      
    - yarn build
  artifacts:
    paths:
      - build

# Stages run sequentially, so we add a new `deploy` stage 
# after the `build` one
  
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public
